
volumes:
  dbdata:
    

services:
  server:
    image: dario61081/nginx-php83-minimal:latest  
    container_name: dev-server
    ports:
      - "15080:80"
    volumes:
      - ./html:/var/www/html
    links: 
      - db
    depends_on:
      - db
  
  db:
    image: mysql/mysql-server:8.0.32
    container_name: dev-db
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_spanish2_ci
      - --lower_case_table_names=1
      - --log_bin_trust_function_creators=1
    volumes:
      - ./dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev-phpmyadmin
    ports:
      - "15081:80"
    environment:
      - PMA_HOST=db
      # - PMA_USER=app
      # - PMA_PASSWORD=app
    depends_on:
      - db    
    links:
      - db

  redis:
    image: redis:alpine
    container_name: dev-redis
    ports:
      - "15082:6379"
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: dev-redis-commander
    ports:
      - "15083:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    links:
      - redis
    depends_on:
      - redis
  
